version: '3.7'

services:
    django:
        tty: true
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - 8000:8000
        environment:
            - DATABASE_ENGINE=django.db.backends.postgresql
            - DATABASE_DB=database
            - DATABASE_USER=django_user
            - DATABASE_PASSWORD=password
            - DATABASE_HOST=postgres
            - DATABASE_PORT=5432
        depends_on:
            - postgres

    postgres:
        image: postgres
        volumes:
            - ./.data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=django_user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=database